name: Build & Publish to GHCR

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'                 # npr. v0.1.0
  workflow_dispatch:

permissions:
  contents: read
  packages: write            # obvezno za push na ghcr.io

env:
  IMAGE: ghcr.io/${{ github.repository }}   # ghcr.io/OWNER/REPO

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=ref,event=tag                 # vX.Y.Z ob tagu
            type=raw,value=latest,enable={{ is_default_branch }}  # latest na default branchu
            type=sha,format=long               # fallback: sha
          labels: |
            org.opencontainers.image.source=${{ github.repository }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./container/Dockerfile        # spremeni, če je Dockerfile drugje
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
